/**
 * tps init — First-run onboarding for TPS.
 *
 * Scaffolds a new TPS workspace:
 *   1. Creates ~/.tps/ directory structure
 *   2. Generates Ed25519 identity key
 *   3. Writes a starter agent.yaml
 *   4. Registers identity with Flair (if reachable)
 *   5. Sends a hello-world task to itself as a smoke test
 */

import { mkdirSync, writeFileSync, existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { homedir } from "node:os";
import { generateKeyPairSync } from "node:crypto";

export interface InitArgs {
  agentId?: string;
  name?: string;
  flairUrl?: string;
  model?: string;
  force?: boolean;
}

const DEFAULT_MODEL = "anthropic/claude-sonnet-4-6";
const DEFAULT_FLAIR = "http://127.0.0.1:9926";

function generateEd25519Key(keyPath: string, pubPath: string): void {
  const { privateKey, publicKey } = generateKeyPairSync("ed25519");
  const privDer = privateKey.export({ type: "pkcs8", format: "der" }) as Buffer;
  // Store raw 32-byte seed (bytes 16–48 of pkcs8)
  writeFileSync(keyPath, privDer.subarray(16), { mode: 0o600 });
  const pubDer = publicKey.export({ type: "spki", format: "der" }) as Buffer;
  writeFileSync(pubPath, pubDer.subarray(12).toString("hex") + "\n", { mode: 0o644 });
}

function agentYaml(agentId: string, model: string, flairUrl: string): string {
  const home = homedir();
  return `# TPS Agent config — generated by tps init
agentId: ${agentId}
name: ${agentId}
workspace: ${join(home, "ops", agentId)}
mailDir: ${join(home, ".tps", "mail")}
memoryPath: ${join(home, ".tps", "agents", agentId, "memory.jsonl")}
contextWindowTokens: 200000

llm:
  model: ${model}

flair:
  url: ${flairUrl}
  keyPath: ${join(home, ".tps", "identity", `${agentId}.key`)}
`;
}

async function registerWithFlair(
  agentId: string,
  name: string,
  flairUrl: string,
  keyPath: string,
): Promise<boolean> {
  try {
    const { createPrivateKey, sign } = await import("node:crypto");
    const raw = readFileSync(keyPath);
    const pkcs8Header = Buffer.from("302e020100300506032b657004220420", "hex");
    const privKey = createPrivateKey({ key: Buffer.concat([pkcs8Header, Buffer.from(raw)]), format: "der", type: "pkcs8" });

    const pubKeyHex = (await import("node:fs")).readFileSync(keyPath.replace(".key", ".pub"), "utf-8").trim();
    const ts = Date.now().toString();
    const nonce = Math.random().toString(36).slice(2, 10);
    const urlPath = "/Identity";
    const payload = `${agentId}:${ts}:${nonce}:POST:${urlPath}`;
    const sig = sign(null, Buffer.from(payload), privKey).toString("base64");
    const auth = `TPS-Ed25519 ${agentId}:${ts}:${nonce}:${sig}`;

    const res = await fetch(`${flairUrl}${urlPath}`, {
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: auth },
      body: JSON.stringify({ agentId, name, role: "agent", publicKey: pubKeyHex }),
    });
    return res.status === 200 || res.status === 201 || res.status === 204;
  } catch {
    return false;
  }
}

export async function runInit(args: InitArgs): Promise<void> {
  const home = homedir();
  const agentId = args.agentId ?? "my-agent";
  const name = args.name ?? agentId;
  const flairUrl = args.flairUrl ?? process.env.FLAIR_URL ?? DEFAULT_FLAIR;
  const model = args.model ?? DEFAULT_MODEL;

  const tpsRoot = join(home, ".tps");
  const identityDir = join(tpsRoot, "identity");
  const agentDir = join(tpsRoot, "agents", agentId);
  const mailDir = join(tpsRoot, "mail", agentId);
  const workspaceDir = join(home, "ops", agentId);
  const keyPath = join(identityDir, `${agentId}.key`);
  const pubPath = join(identityDir, `${agentId}.pub`);
  const configPath = join(agentDir, "agent.yaml");

  // Guard against overwrite
  if (existsSync(configPath) && !args.force) {
    console.error(`Agent '${agentId}' already exists at ${configPath}`);
    console.error("Use --force to overwrite.");
    process.exit(1);
  }

  console.log(`\n⚒️  TPS Init — setting up agent '${agentId}'\n`);

  // 1. Directory structure
  for (const d of [identityDir, agentDir, join(mailDir, "new"), join(mailDir, "cur"), join(mailDir, "tmp"), workspaceDir]) {
    mkdirSync(d, { recursive: true });
  }
  console.log(`✓ Directories created under ~/.tps/`);

  // 2. Ed25519 identity
  if (!existsSync(keyPath) || args.force) {
    generateEd25519Key(keyPath, pubPath);
    console.log(`✓ Ed25519 identity generated: ~/.tps/identity/${agentId}.key`);
  } else {
    console.log(`  Identity already exists — skipping key generation`);
  }

  // 3. agent.yaml
  writeFileSync(configPath, agentYaml(agentId, model, flairUrl), { mode: 0o644 });
  console.log(`✓ Agent config written: ~/.tps/agents/${agentId}/agent.yaml`);

  // 4. Workspace README
  writeFileSync(join(workspaceDir, "SOUL.md"), `# ${name}\n\nAgent workspace. Edit to define identity.\n`, { mode: 0o644 });
  console.log(`✓ Workspace created: ~/ops/${agentId}/`);

  // 5. Flair registration
  process.stdout.write(`  Registering with Flair at ${flairUrl}... `);
  const registered = await registerWithFlair(agentId, name, flairUrl, keyPath);
  if (registered) {
    console.log("✓ registered");
  } else {
    console.log("⚠ skipped (Flair not reachable — run later with: tps identity register --id " + agentId + ")");
  }

  console.log(`
✅ Done! Agent '${agentId}' is ready.

Next steps:
  tps auth login anthropic          # authenticate with your LLM provider
  tps agent start --id ${agentId}   # start the agent runtime
  tps roster show ${agentId}        # verify Flair registration

Docs: https://docs.tps.dev
`);
}
