import { launchFlagDefinitions } from "./nono.js";

export const cliFlagDefinitions = {
  reason: { type: "string" },
  expiresIn: { type: "string" },
  trust: { type: "string" },
  pubkey: { type: "string" },
  encPubkey: { type: "string" },
  name: { type: "string" },
  workspace: { type: "string" },
  dryRun: { type: "boolean", default: false },
  json: { type: "boolean", default: false },
  config: { type: "string" },
  deep: { type: "boolean", default: false },
  summary: { type: "string" },
  channel: { type: "string" },
  branch: { type: "boolean", default: false },
  manifest: { type: "string" },
  soundstage: { type: "boolean", default: false },
  quietNonoCheck: { type: "boolean", default: false },
  nonono: { type: "boolean", default: false },
  ...launchFlagDefinitions,
  inject: { type: "boolean", default: true },
  runtime: { type: "string", default: "openclaw" },
  baseModel: { type: "string" },
  since: { type: "string" },
  limit: { type: "number" },
  interval: { type: "number" },
  daemon: { type: "string" },
  from: { type: "string" },
  clone: { type: "boolean", default: false },
  overwrite: { type: "boolean", default: false },
  schedule: { type: "string" },
  keep: { type: "number" },
  sanitize: { type: "boolean", default: true },
  listen: { type: "number" },
  host: { type: "string" },
  force: { type: "boolean", default: false },
  follow: { type: "boolean", default: false },
  lines: { type: "number" },
  transport: { type: "string" },
  port: { type: "number" },
  autoPrune: { type: "boolean", default: false },
  prune: { type: "boolean", default: false },
  staleMinutes: { type: "number" },
  offlineHours: { type: "number" },
  shared: { type: "boolean", default: false },
  cost: { type: "boolean", default: false },
  costs: { type: "boolean", default: false },
  today: { type: "boolean", default: false },
  agent: { type: "string" },
  statusOverride: { type: "string" },
  desc: { type: "string" },
  id: { type: "string" },
  fromBeginning: { type: "boolean", default: false },
  count: { type: "boolean", default: false },
  priority: { type: "string" },
  version: { type: "string" },
  verbose: { type: "boolean", default: false },
  tunnelVia: { type: "string" },
  keepUnits: { type: "boolean", default: false },
  noFlair: { type: "boolean", default: false },
  forceReinstallFlair: { type: "boolean", default: false },
  purgeFlair: { type: "boolean", default: false },
  apply: { type: "boolean", default: false },
  expires: { type: "string" },
  expiresWithin: { type: "string" },
  fix: { type: "boolean", default: false },
  flairKeysDir: { type: "string" },
  identityDir: { type: "string" },
  keysDir: { type: "string" },
  nonInteractive: { type: "boolean", default: false },
  owner: { type: "string" },
  path: { type: "string" },
  scope: { type: "string" },
  secretsDir: { type: "string" },
  sensitivity: { type: "string" },
  credType: { type: "string" },
  check: { type: "boolean", default: false },
  noGuard: { type: "boolean", default: false },
  staleOnly: { type: "boolean", default: false },
  root: { type: "string" },
  failOnDrift: { type: "boolean", default: false },
  noVerify: { type: "boolean", default: false },
  verifyPreview: { type: "boolean", default: false },
  task: { type: "string" },
  taskId: { type: "string" },
  title: { type: "string" },
  spec: { type: "string" },
  output: { type: "string" },
  taskContext: { type: "string" },
  stdin: { type: "boolean", default: false },
  unsigned: { type: "boolean", default: false },
  replyTo: { type: "string" },
  messageId: { type: "string" },
} as const;

export const cliOptionTypes = new Map<string, (typeof cliFlagDefinitions)[keyof typeof cliFlagDefinitions]["type"]>(
  Object.entries(cliFlagDefinitions).flatMap(([name, flag]) =>
    [...new Set([name, name.replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`)])]
      .map((spelling) => [`--${spelling}`, flag.type] as const)
  )
);

export function cliOptionConsumesValue(arg: string, next: string | undefined): boolean {
  const type = cliOptionTypes.get(arg);
  return type !== undefined && type !== "boolean" && next !== undefined &&
    (!next.startsWith("-") || /^-([0-9]+(\.[0-9]+)?|\.[0-9]+)$/.test(next) || next === "--help" || next === "-h" || next === "--version" || next === "-v");
}
